name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

# This seems to be broken and it's not clear why:
#
#  Error: could not import github.com/connorkuehl/wording/internal/service
#  (-: could not load export data: no export data for
#  "github.com/connorkuehl/wording/internal/service") (typecheck)
#
# lint:
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/checkout@v2
#     - name: golangci-lint
#       uses: golangci/golangci-lint-action@v3
#       with:
#         # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
#         version: v1.50
